version: '3'
services:
  golang:
    image: golang:1.19.3-alpine
    container_name: go_container
    working_dir: /app
    restart: always
    volumes:
      - ./backend/go:/app
      - ./configuration/go/Database.go:/app/Config/Database.go
    ports:
      - 8080:3000
    command: "go run /app/main.go"
    networks:
      - vlsg_network
